### ISSUE TITLE
下载、登录等信息在关闭后不会保存

### ISSUE THREAD

**Issue by sxyzy1016** [bestwu/docker-thunderspeed#1]
应该用这个的都是国内的吧。。我就用中文了Orz
迅雷的数据没有保存。容器（迅雷）关闭之后再打开的时候下载项会全部消失且没有办法重新导入，迅雷账户也必须要重新登录。
是不是考虑把/home/thunderspeed/.deepinwine也做成VOLUME？

**Comment by top-bettercode** [comment]
不删除容器应该不会出现这种情况，你是不是用了 --rm

**Comment by sxyzy1016** [comment]
...好吧，是我强迫症了:D

**Comment by top-bettercode** [comment]
docker pull bestwu/thunderspeed 最新镜像，可映射 $HOME/.thunderspeed:/home/thunderspeed/.thunderspeed 永久保存登录及下载列表

**Comment by sxyzy1016** [comment]
Nice One！非常感谢！
