### ISSUE TITLE
miss winemenubuilder.exe

### ISSUE THREAD

**Issue by jt6562** [bestwu/docker-thunderspeed#2]
$ docker logs thunderspeed -f                    
启动 ThunderSpeed

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,16 CPUs Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (206D7),ASM,AES-NI)

Scanning the drive for archives:
1 file, 61290518 bytes (59 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-ThunderSpeed/files.7z
--
Path = /opt/deepinwine/apps/Deepin-ThunderSpeed/files.7z
Type = 7z
Physical Size = 61290518
Headers Size = 13525
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 171
Files: 1269
Size:       172250383
Compressed: 61290518
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
Could not load wine-gecko. HTML rendering will be disabled.
wine: configuration in '/home/thunderspeed/.deepinwine/Deepin-ThunderSpeed' has been updated.

**Comment by top-bettercode** [comment]
wine: cannot find L"C:\windows\system32\winemenubuilder.exe" 此报错，不影响使用
